version: '3.4'

services:
  api-boberto-services:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: web/Dockerfile
    env_file: .env
    ports:
      - "5001:80"
    volumes:
      - ./:/api
      - /var/run/docker.sock:/var/run/docker.sock
